homeassistant:
  name: Smart Home
  time_zone: Europe/Prague
  unit_system: metric

logger:
  default: info
  logs:
    homeassistant.components.assist_pipeline: debug
    homeassistant.components.ollama: info
    homeassistant.components.wyoming: info

default_config:

automation: !include automations.yaml
script: !include scripts.yaml
